### ISSUE TITLE
panic: user: Current not implemented on linux/amd64

### ISSUE THREAD

**Issue by wkentaro** [caarlos0/antibody#61]
On Linux 14.04::
I have this error:

```
% ./antibody/bin/antibody
panic: user: Current not implemented on linux/amd64

goroutine 1 [running]:
github.com/caarlos0/gohome.home(0x0, 0x0)
	/Users/carlos/Code/Go/src/github.com/caarlos0/gohome/main.go:67 +0x9f
github.com/caarlos0/gohome.xdgCache(0x0, 0x0)
	/Users/carlos/Code/Go/src/github.com/caarlos0/gohome/main.go:55 +0x72
github.com/caarlos0/gohome.cacheFor(0x510610, 0x8, 0x509cd0, 0x5, 0x0, 0x0)
	/Users/carlos/Code/Go/src/github.com/caarlos0/gohome/main.go:29 +0x1f8
github.com/caarlos0/gohome.Cache(0x510610, 0x8, 0x0, 0x0)
	/Users/carlos/Code/Go/src/github.com/caarlos0/gohome/main.go:13 +0x57
github.com/caarlos0/antibody.Home(0x0, 0x0)
	/Users/carlos/Code/Go/src/github.com/caarlos0/antibody/api.go:70 +0x7a
main.main()
	/Users/carlos/Code/Go/src/github.com/caarlos0/antibody/cmd/antibody/main.go:15 +0xbe

goroutine 2 [runnable]:
runtime.forcegchelper()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.go:90
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mgc0.go:82
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.go:712
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by wkentaro** [comment]
related to https://github.com/golang/go/issues/6376 ?

**Comment by wkentaro** [comment]
worked with v0.2.0.
did not v0.2.2.

**Comment by caarlos0** [comment]
@wkentaro yeah, the problem is in https://github.com/caarlos0/gohome/ .

I fixed it there in https://github.com/caarlos0/gohome/pull/3, but forgot to re-release here.

Releasing v0.2.3 right now...

**Comment by caarlos0** [comment]
@wkentaro done.

Let me know if there still any issue.

Thanks
